# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - webappfastapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://contregapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_80e5ebf4de7d41ab85ea8a3485ae7baa }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1fb99bfd98294c39ac962024aeccbf1f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: contregapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_80e5ebf4de7d41ab85ea8a3485ae7baa }}/pr_34_fastpai:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'webappfastapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6403d2d7918e408aa2a8a893594f24df }}
        images: 'contregapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_80e5ebf4de7d41ab85ea8a3485ae7baa }}/pr_34_fastpai:${{ github.sha }}'